### ISSUE TITLE
Sort access to this repo

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/style#20]
Previously Jimmy was the maintainer of this repo. Since he's no longer active we're a bit stuck.
While this repo isn't especially active, we should know who and how to update it.
It probably does make sense that this continue to have a very limited number of contributors though -- our style is something which should be changing only very slowly and in a considered manner.

**Comment by PeterJCLaw** [comment]
@Scarzy perhaps it would make sense for you (on behalf of the trustees) to take this one?

**Comment by sedders123** [comment]
Now we have the Marketing team think this is solved.
