### ISSUE TITLE
Official blue differs from logo colour

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/style#5]
This makes the style somewhat confusing and hard to comply with, particularly when embedding the logo on a blue background (see the IDE).

**Comment by PeterJCLaw** [comment]
@jimmythompson any thoughts on this?

**Comment by jimmythompson** [comment]
I agree, they should be consistent. I'll sort this out.

As for the IDE, can you try the logo in white rather than the bordered blue? We can see how it looks. If we aren't both happy with the result, I'll prepare a bordered logo for the style guide.

**Comment by PeterJCLaw** [comment]
I'm not quite sure what you mean by "in white"?

The IDE currently has a blue top bar and a main white body. The logo is featured as part of the top bar, so currently is a white circle with the stylised SR also in white, all on the same blue field as the top bar.

In order for the spinner to do anything we need a border somewhere which can become the spinner pieces when active. Therefore we need a border contrast, which I'm guessing is why this was setup as it is (I didn't design or construct the original).

Are you suggesting that we use a variant of the logo which is blue symbols on a white field? If so, I think that that would be ok as a static item, though we'd lose the spinner. Given that the spinner is actually useful (it tells the user that things are loading), I'd rather not lose it.

**Comment by PeterJCLaw** [comment]
We now have a new logo and a new colour, so this is redundant.
